### PR TITLE
fix: fix EntrypointLookup Exception

### PR DESCRIPTION
**Pull request by jeremyFreeAgent**
Before it was:

```
Could not find the entry "fake_entry" in "...". Found: entrypoints.
```

### CODE REVIEW

**Comment by weaverryan** [comment]
Thanks for this @jeremyFreeAgent!

We're getting a test failure with the lowest deps... `expectExceptionMessageMatches` is not defined, which is odd since that happens on PHPUnit `7.5.20`, but that same version of PHP passes in another build on the matrix.

**Comment by jeremyFreeAgent** [comment]
I didn't test it with that version in local. I'll look for it today to see why it is failing!

**Comment by jeremyFreeAgent** [comment]
Work well with 7.3.26 and PHPUnit 7.5.20 in local. Very odd.

**Comment by jeremyFreeAgent** [comment]
I reproduced the anomaly with installing dependencies as it is done in Travis (for 7.3 with low deps).
Maybe with `symfony/phpunit-bridge (5.x-dev)`.

**Comment by weaverryan** [comment]
Thanks for checking into this further! Could we bump phpunit-bridge to a higher version? I don't see any downside to that, as it's a dev-dependency anyways.

**Comment by jeremyFreeAgent** [comment]
I'm going to try that!

**Comment by jeremyFreeAgent** [comment]
@weaverryan what do you think?

**Comment by weaverryan** [comment]
Thanks Jérémy! Sorry for letting this sit for so long :)

**Comment by jeremyFreeAgent** [comment]
Don’t worry! Happy to help ♥️

**Pull request merged**
