### PR TITLE
[Contracts] Update dependency to use symfony/service-contracts

### LINKED ISSUE #64: Symfony 4.3 / Composer:  Ambiguous class resolution for symfony/contracts
Using this bundle (v1.6.0) with Symfony 4.3 will have Composer generate a couple of "Warning: Ambiguous class resolution" when trying to generate an optimized autoloader.

`$ composer dump-autoload --optimize`
```
Generating optimized autoload files
Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\CallbackInterface" was found in both "/var/www/vendor/symfony/cache-contracts/CallbackInterface.php" and "/var/www/vendor/symfony/contracts/Cache/CallbackInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\ItemInterface" was found in both "/var/www/vendor/symfony/cache-contracts/ItemInterface.php" and "/var/www/vendor/symfony/contracts/Cache/ItemInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\CacheInterface" was found in both "/var/www/vendor/symfony/cache-contracts/CacheInterface.php" and "/var/www/vendor/symfony/contracts/Cache/CacheInterface.php", the first will be used.
(snip)
```

The framework will load some traits and interfaces from /symfony/service-contracts/ while /webpack-encore-bundle/ will try to load the same from /symfony/contracts/

`$ composer why symfony/contracts`
```
symfony/webpack-encore-bundle  v1.6.0  requires  symfony/contracts (^1.0)  
```

`$ composer why symfony/service-contracts`
```
symfony/cache                 v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/console               v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/dependency-injection  v4.3.0  requires  symfony/service-contracts (^1.1.2)  
symfony/doctrine-bridge       v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/expression-language   v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/monolog-bridge        v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/security-core         v4.3.0  requires  symfony/service-contracts (^1.1)    
symfony/stopwatch             v4.3.0  requires  symfony/service-contracts (^1.0)   
```

Could this bundle bump it's requirement to symfony/service-contracts too?

### PR DESCRIPTION
**Pull request by wbrinkman**
Updated requirement symfony/contracts to symfony/service-contracts so having this bundle in a Symfony 4.3 installation does not generate ambiguous classes with an optimized composer autoloader.

Fixes #64

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by vkhramtsov** [comment]
@wbrinkman @nicolas-grekas Any news here?

**Review by javiereguiluz — APPROVED** [review]

**Comment by javiereguiluz** [comment]
I just saw this in the Symfony Demo app. Looking forward to the merge and new version release! Thank you.

```
$ composer dump-autoload -o

Restricting packages listed in "symfony/symfony" to "4.3.*"
Generating optimized autoload files

Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\CallbackInterface" was found in both "vendor/symfony/cache-contracts/CallbackInterface.php" and "vendor/symfony/contracts/Cache/CallbackInterface.php", the first will be used.

Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\ItemInterface" was found in both "vendor/symfony/cache-contracts/ItemInterface.php" and "vendor/symfony/contracts/Cache/ItemInterface.php", the first will be used.

Warning: Ambiguous class resolution, "Symfony\Contracts\Cache\CacheInterface" was found in both "vendor/symfony/cache-contracts/CacheInterface.php" and "vendor/symfony/contracts/Cache/CacheInterface.php", the first will be used.

[...]
```

**Comment by javer** [comment]
Any update on this?
I see 25 warnings every time I run composer in Symfony 4.3 project with this bundle.

**Review by vkhramtsov — APPROVED** [review]

**Comment by javer** [comment]
@weaverryan Could you please press "Merge pull request" button and make a new release? We already have 3 approvals in this PR.

**Comment by tompiard** [comment]
I love how webpack encore improved my frontend workflow in so many ways. But the wait for this PR is very worrisome. It is a very basic commit that keep this bundle in sync with the Symfony ecosystem that it's supposed to be part of.

**Comment by luispabon** [comment]
Anybody else have merge & versioning rights that could possibly push this through the finishing line pls?

**Comment by javer** [comment]
@weaverryan @nicolas-grekas @fabpot Please help someone to press Merge button in this PR, which is ready for a month, has 3 approvals and have just been ignored one more time during creating a new release 5 hours ago.

**Comment by weaverryan** [comment]
Sorry - will merge tonight. This bundle is my responsibility and I’ve been a bit busy - apologies for the inconvenience!

**Comment by weaverryan** [comment]
Thank you @wbrinkman! And sorry again for the delay - thanks for everyone's patience!

**Comment by luispabon** [comment]
Thank you @weaverryan :+1:

**Pull request merged**
