### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
~I think it's too early to allow Symfony 6 anywhere. The reason is that we're not done yet with adding BC breaks (aka return types) to it.~

**Comment by Nyholm** [comment]
Allowing people (CI) to install this bundle with Symfony CI is not the same as guarantee that it will work. 

I understand what using dev-main means. I know that Im really living on the edge and things might/will change. 

Strictly speaking: We are not done adding BC breaks until November.

**Comment by nicolas-grekas** [comment]
Then, merging this PR will block any releases of the bundle.

**Comment by Nyholm** [comment]
No, I would not agree with that. =)

**Comment by jdreesen** [comment]
This was also discussed in #136

**Comment by Nyholm** [comment]
I slept on in. I see what @nicolas-grekas is saying. 

> I think it's too early to allow Symfony 6 anywhere. The reason is that we're not done yet with adding BC breaks (aka return types) to it.

You mean to THIS package. I though you referred to Symfony. 

I agree with you. Merging this PR now is premature.

**Comment by nicolas-grekas** [comment]
Topic unlocked! I also reopened #136. I'll let you decide which one to keep and which one to close :)

**Comment by jrushlow** [comment]
going to close this in favor of PR #136 as it was opened first. Thanks @Nyholm for the help on this!

**Pull request closed without merging**
