### PR TITLE
Allow disabling default build if multiple entry points are defined

### LINKED ISSUE #32: Optional default entrypoint when using multiple entrypoints
I'm trying out multiple entrypoints, and first test was to define a single `builds` directive:

```
webpack_encore:
    builds:
        frontend: '%kernel.project_dir%/web/build'
```

However, Webpack Encore complains that the `output_path` is not configured: `The child node "output_path" at path "webpack_encore" must be configured.`. Is this the intended behaviour? How would I go about specifying this kind of config as a starting point for other developers on my team to extend with more entrypoints?

### PR DESCRIPTION
**Pull request by emodric**
Fixes #32.

### CODE REVIEW

**Review by weaverryan — CHANGES_REQUESTED** [review]
Hey @emodric!

Sorry for the slow attention on this. I merged another PR and created conflicts with this one - could you check those?

I'm +1 for this PR. However, I'm interested in what the error is if you disable the default entrypoint, and then accidentally use a feature without specifying which build you want - I think the user will see errors like "The build _default does not exist" - which isn't a great error.

**Comment by weaverryan** [comment]
#45 will also help and affect this PR

**Comment by emodric** [comment]
@weaverryan Will get back to you next week, can't get to it any sooner.

**Comment by emodric** [comment]
@weaverryan I've pushed the rebased commit. As for #45, how will it help and affect this PR?

When someone uses a default build which has been disabled, the error message is: `Given entry point "_default" is not configured`.

Maybe we could try to determine which builds are configured and offer them as an alternative in the error message, e.g: `The default build is not enabled. Use one of "frontend", "backend", "app1", "app2" builds.`

**Comment by jRexhmati** [comment]
Hello @emodric do you plan to merge this pr anytime soon?

**Comment by emodric** [comment]
You should probably be asking @weaverryan that :)

**Comment by jRexhmati** [comment]
@emodric  Thanks for the info :)
@weaverryan Do you plan to merge this soon? I can give you a hand ✋if you need

**Review by weaverryan — APPROVED** [review]

**Comment by weaverryan** [comment]
Sorry about the slow merge on this - it's a really great PR. Even the README got updated! Thank you Edi!

**Comment by emodric** [comment]
@weaverryan Thanks for the merge :)

However, what about this part, that you were initially concerned about?

> Maybe we could try to determine which builds are configured and offer them as an alternative in the error message, e.g: The default build is not enabled. Use one of "frontend", "backend", "app1", "app2" builds.

**Pull request merged**
