### PR TITLE
Reset assets on FINISH_REQUEST.

### LINKED ISSUE #90: Ability to "reset" cache of rendered files automatically in Twig
Related #87 

When you `encore_entry_link_tags()` or `encore_entry_script_tags()` tags, the bundle "remembers" which CSS and JS files have been rendered and avoids rendering them again. This is by design: it allows you to render multiple "entries" on the same page and avoid link/script tags for the same CSS & JS files (due to code splitting).

But, this has some nasty side effects. One practical one is sending emails and using these functions to import your CSS. If you have Messenger installed, each Email is technically rendered twice - and the second (real) email will contain *no* CSS link tags. The problem is probably worse when sending emails through the queue - as I think once a worker has sent one email, the rest won't contain CSS link tags.

The best solution would be to reset "automatically" the cache after a "main" Twig rendering (e.g. a call to`$twig->render()`) but no such concept currently exists in Twig.

A more immediate solution may be to allow users to "opt out" of the cache via some argument to `encore_entry_link_tags()`.

### PR DESCRIPTION
**Pull request by Warxcell**
Fixes #90, #94

### CODE REVIEW

**Comment by weaverryan** [comment]
Sorry for the slow merge - thank you @Warxcell!

**Comment by blankse** [comment]
@weaverryan After upgrading to v1.14.0 I have following error:
I have 2 entrypoints in my webpage. One on the top and one on the bottom. In v1.13.2 the runtime.js from webpack is only loaded in the entrypoint on the top. Now it is also loaded at the bottom and scripts are executed twice which makes makes mistackes (double click events...)

What can I do to have the runtime.js only on top?

**Comment by Warxcell** [comment]
Hm, do you have sub-requests in-between? Can you provide reproducible code in some repo so I can fork and add a fix? Or directly add test case ?

**Comment by blankse** [comment]
@Warxcell Yes there are sub-requests in-between. I can try to give you an reproducible code example.

**Comment by noahduncan** [comment]
We're seeing similar issues with duplicate runtime.js script tags for our code.  I see use cases both ways, sometimes you want your all script tags on every request, sometimes you don't.  To me, that makes it feel like the option should be configurable  somewhere.

**Comment by scrummer** [comment]
@Warxcell @weaverryan We also ran into the problem, that one of our projects kept loading the runtime.js multiple times. In our case it lead to forms being sent multiple times (including submission emails). Really had to look deep to figure out why it did that.
However; I kind of get the point why you guys implemented that feature. For us, this problem occured in the Pimcore ecosystem which uses (depending on the use-case) some up to a lot sub-requests.

As already stated; from a developers perspective I totally understand why you implemented that, but I think this sub-request thingy could break a lot of stuff. We were happy that it was "just" a contact form. I was wondering what would've happened if we updated the bundle in one of our larger shop systems (multiple orders? multiple items in the cart by accident? etc etc).

Unfortunately I can't really think of a "better" alternative than the Request-Finished event. But I think it really makes sense to think about it, how it could impact users.

Thank you, stay healthy!

BR,
Jan

**Comment by H4wKs** [comment]
@Warxcell as @zing-james explained in #166, if you use the twig render function you end up with runtime.js being load twice, this is a huge side effect as I believe many people (including myself) use this in their projects.

**Comment by kuldippujara** [comment]
Hi @Warxcell, @weaverryan,

I am having the same issue with embed controller after the update. I have check the other use cases where users want to reset the assets. I want to provide a suggestion that if we can differentiate the sub requests then we can put the condition when we want to reset and when we don't want to. 

1 option is to add attribute in request similar to _format eg. _renderer : inline / fragment
which will be only available if its render by Fragment renderer. 
then we can fix both the scenarios. 

waiting for feedback. 

Happy to create PR for Symfony and add attribute and then create PR to fix the issue.

**Comment by Warxcell** [comment]
> 1 option is to add attribute in request similar to _format eg. _renderer : inline / fragment which will be only available if its render by Fragment renderer. then we can fix both the scenarios.


Sounds ok to me.

**Pull request merged**
